#
#    CC BY-NC-ND 4.0 license
train:
  snapshot_save_iterations: 1000 # How often do you want to save trained models
  image_save_iterations: 200 # How often do you want to save output images during training
  image_display_iterations: 50
  display: 1 # How often do you want to log the training stats
  snapshot_prefix: /mnt/lustre/zhuxinge/UNIT_Bird/src/outputs/unit_large_six/ # Where do you want to save the outputs
  hyperparameters:
    trainer: COCOGANTrainer_six
    para: 0
    lr: 0.0001             # learning rate
    ll_direct_link_w: 100  # weight on the self L1 reconstruction loss
    kl_direct_link_w: 0.1 # weight on VAE encoding loss
    ll_direct_link_c: 10
    ll_cycle_link_w: 100   # weight on the cycle L1 reconstruction loss
    kl_cycle_link_w: 0.1  # weight on the cycle L1 reconstruction loss
    gan_c: 1
    gan_w: 10              # weight on the adversarial loss
    batch_size: 4          # image batch size per domain
    max_iterations: 500000 # maximum number of training epochs
    gen:
      name: COCOResGen_six
      ch: 64               # base channel number per layer
      input_dim_a: 6
      input_dim_b: 3
      input_dim_c: 3
      n_enc_front_blk: 3
      n_enc_res_blk: 3
      n_enc_shared_blk: 1
      n_gen_shared_blk: 1
      n_gen_res_blk: 3
      n_gen_front_blk: 3
    dis:
      name: COCODis_six
      ch: 64
      input_dim_a: 6
      input_dim_b: 3
      input_dim_c: 3
      n_layer: 6
  datasets:
    train_a: # Domain 1 dataset
      channels: 3       # image channel number
      scale: 1.2
      crop_image_height: 192 # crop image size
      crop_image_width: 320  # crop image size
      class_name: dataset_imagenet_image    # dataset class name
      root: /mnt/lustre/zhuxinge/dataset/unit_large_320/
      folder: day_car_homo
      list_name: day_car_homo_list.txt  # image list
    train_b: # Domain 2 dataset
      channels: 3       # image channel number
      scale: 1.2
      crop_image_height: 192 # crop image size
      crop_image_width: 320  # crop image size
      class_name: dataset_imagenet_image    # dataset class name
      root: /mnt/lustre/zhuxinge/dataset/unit_large_320/
      folder: day_car_gt
      list_name: day_car_gt_list.txt  # image list
    train_c: # Domain 2 dataset
      channels: 3       # image channel number
      scale: 1.2
      crop_image_height: 192 # crop image size
      crop_image_width: 320  # crop image size
      class_name: dataset_imagenet_image    # dataset class name
      root: /mnt/lustre/zhuxinge/dataset/unit_large_320/
      folder: day_car_new
      list_name: day_car_new_list.txt  # image list
